name: Verify Clarity Contracts
on:
  pull_request:
    branches: [main]
    paths:
      - "**.clar"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get full history for detecting changes

      - name: Verify Clarity Contracts
        id: verify
        uses: proj-clarity-esbmc/clara_github_action@v0.1.4-alpha
        with:
          contracts_dir: "./contracts"
          fail_on_issue: "true"

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.verify.outputs.sarif_report != ''
        with:
          sarif_file: ${{ steps.verify.outputs.sarif_report }}
